name: Publish Docker image of Expansion Gateway Leader in docker hub
run-name: ${{ github.actor }} is publishing the Expansion Gateway Leader image in docker hub
on:
    push:
        branches:
            - 'master'

jobs:
    push_to_expansion_docker_hub:
        name: Push Docker image to registry
        runs-on: ubuntu-latest
        environment: secrets
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: Check out the repo
              uses: actions/checkout@v5

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                images: merkelnotmerz/area-a01i01

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                context: .
                file: ./Dockerfile.leader
                push: true
                tags: merkelnotmerz/area-a01i01:1.0.0-alpine3.22.2
                labels: ${{ steps.meta.outputs.labels }}

            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@v3
              with:
                subject-name: index.docker.io/merkelnotmerz/area-a01i01
                subject-digest: ${{ steps.push.outputs.digest }}
                push-to-registry: true
